<?php
/*
 * Copyright (C) 2018 emerchantpay Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * @author      emerchantpay
 * @copyright   2018 emerchantpay Ltd.
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2 (GPL-2.0)
 */
?>
<?php $_code = $this->getMethodCode() ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<?php if ($this->getHasNominalItems()) { ?>
		<li>
			<ul class="messages">
				<li class="notice-msg">
					<ul>
						<li>
							<span><?php echo $this->__("Please have in mind that you are processing a Recurring Transaction!");?></span>
						</li>
					</ul>
				</li>
			</ul>
		</li>
	<?php } ?>
	<li>
		<p>
			<?php echo $this->__("You will be redirected to our partner's website, where you can safely pay with your credit card."); ?>
		</p>
	</li>
</ul>