<?php
/*
 * Copyright (C) 2018 emerchantpay Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * @author      emerchantpay
 * @copyright   2018 emerchantpay Ltd.
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU General Public License, version 2 (GPL-2.0)
 */
?>
<!DOCTYPE>
<html>
<head>
    <title><?php echo $this->__('You are being redirected!'); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <style>
        html,body {
            margin:0;
            padding:0;
            width:100%;
            height:100%;
            display:table;
        }
        .wrapper {
            text-align:center;
            display:table-cell;
            vertical-align:middle;
        }
        .notice {
            padding:16px;
        }
    </style>
</head>
<body>

<div class="wrapper">
    <div class="notice">
        <p>
            <?php echo $this->__("You are being redirected to a secure page, where you can complete your payment!"); ?>
        </p>
    </div>
    <div class="form">
        <?php echo $this->generateForm(); ?>
    </div>
</div>

<script type="text/javascript">
    window.setTimeout(
        function() {
            document.getElementById("<?php echo $this->getButtonId(); ?>").click();
        }, 3000
    );
</script>
</body>
</html>