<!DOCTYPE>
<html>
<head>
    <title><?php echo $this->__('You are being redirected!'); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <style>
        html,body {
            margin:0;
            padding:0;
            width:100%;
            height:100%;
            display:table;
        }
        .wrapper {
            text-align:center;
            display:table-cell;
            vertical-align:middle;
        }
        .notice {
            padding:16px;
        }
    </style>
</head>
<body>

<div class="wrapper">
    <div class="notice">
        <p>
            <?php echo $this->__("You are being redirected to a secure page, where you can complete your payment!"); ?>
        </p>
    </div>
    <div class="form">
        <?php echo $this->generateForm(); ?>
    </div>
</div>

<script type="text/javascript">
    window.setTimeout(
        function() {
            document.getElementById("<?php echo $this->getButtonId(); ?>").click();
        }, 3000
    );
</script>
</body>
</html>